// Cloudflare Pages Edge Function: CORS & API Proxy for CAT AI
// Handles requests to https://api.xkiro.com/v1 and external MCP endpoints

export async function onRequest(context: any): Promise<Response> {
  const { request } = context;
  const url = new URL(request.url);

  // Handle CORS Preflight OPTIONS
  if (request.method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization, x-api-key, x-requested-with, *',
        'Access-Control-Max-Age': '86400',
      },
    });
  }

  // Get target URL from query parameter 'target'
  const targetParam = url.searchParams.get('target');
  let targetUrl = targetParam;

  if (!targetUrl) {
    targetUrl = 'https://api.xkiro.com/v1/chat/completions';
  }

  try {
    const forwardHeaders = new Headers();
    request.headers.forEach((value: string, key: string) => {
      const lowerKey = key.toLowerCase();
      // Skip host / origin headers that should be generated by edge
      if (!['host', 'origin', 'referer', 'cf-ray', 'cf-connecting-ip'].includes(lowerKey)) {
        forwardHeaders.set(key, value);
      }
    });

    // Ensure content type and auth are passed
    if (!forwardHeaders.has('content-type')) {
      forwardHeaders.set('content-type', 'application/json');
    }

    const body = request.method !== 'GET' && request.method !== 'HEAD' ? await request.arrayBuffer() : undefined;

    const proxyResponse = await fetch(targetUrl, {
      method: request.method,
      headers: forwardHeaders,
      body,
    });

    const responseHeaders = new Headers(proxyResponse.headers);
    responseHeaders.set('Access-Control-Allow-Origin', '*');
    responseHeaders.set('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    responseHeaders.set('Access-Control-Allow-Headers', 'Content-Type, Authorization, x-api-key, x-requested-with, *');

    return new Response(proxyResponse.body, {
      status: proxyResponse.status,
      statusText: proxyResponse.statusText,
      headers: responseHeaders,
    });
  } catch (err: any) {
    return new Response(
      JSON.stringify({
        error: {
          message: `Lỗi Cloudflare Edge Proxy: ${err.message || 'Không thể kết nối đến máy chủ đích'}`,
          type: 'edge_proxy_error',
        },
      }),
      {
        status: 502,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      }
    );
  }
}
